-- =========================================================
-- CRUD COMPLETO PRODUCTO - PostgreSQL
-- Tabla equivalente al modelo Django Producto
-- =========================================================

DROP TABLE IF EXISTS productos_producto;

CREATE TABLE productos_producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT NOT NULL,
    precio NUMERIC(10,2) NOT NULL
);

-- =========================================================
-- CREATE
-- =========================================================

INSERT INTO productos_producto (nombre, descripcion, precio)
VALUES
('Notebook Lenovo ThinkPad', 'Notebook empresarial para desarrollo y oficina.', 899990.00),
('Mouse Logitech MX Master', 'Mouse inalámbrico ergonómico de alta precisión.', 79990.00),
('Monitor Samsung 24 pulgadas', 'Monitor Full HD ideal para trabajo y estudio.', 129990.00),
('Teclado Mecánico Redragon', 'Teclado mecánico RGB para programación.', 59990.00);

-- =========================================================
-- READ
-- =========================================================

SELECT *
FROM productos_producto;

SELECT id, nombre, precio
FROM productos_producto;

SELECT *
FROM productos_producto
WHERE id = 1;

SELECT *
FROM productos_producto
WHERE nombre = 'Notebook Lenovo ThinkPad';

SELECT *
FROM productos_producto
WHERE nombre ILIKE '%Samsung%';

SELECT *
FROM productos_producto
WHERE precio > 100000;

SELECT *
FROM productos_producto
WHERE precio BETWEEN 50000 AND 200000;

SELECT *
FROM productos_producto
ORDER BY precio ASC;

SELECT *
FROM productos_producto
ORDER BY precio DESC;

SELECT COUNT(*) AS total_productos
FROM productos_producto;

-- =========================================================
-- UPDATE
-- =========================================================

UPDATE productos_producto
SET precio = 849990.00
WHERE nombre = 'Notebook Lenovo ThinkPad';

UPDATE productos_producto
SET
    nombre = 'Notebook Lenovo ThinkPad Pro',
    descripcion = 'Notebook empresarial actualizado con mejor precio.',
    precio = 999990.00
WHERE nombre = 'Notebook Lenovo ThinkPad';

UPDATE productos_producto
SET precio = precio * 0.90
WHERE precio > 500000;

-- =========================================================
-- READ DESPUÉS DEL UPDATE
-- =========================================================

SELECT *
FROM productos_producto
ORDER BY id ASC;

-- =========================================================
-- DELETE
-- =========================================================

DELETE FROM productos_producto
WHERE nombre = 'Mouse Logitech MX Master';

DELETE FROM productos_producto
WHERE precio < 10000;

-- =========================================================
-- READ FINAL
-- =========================================================

SELECT *
FROM productos_producto
ORDER BY id ASC;

-- =========================================================
-- OPCIONAL: VACIAR TABLA COMPLETA
-- Cuidado: esto elimina todos los registros
-- =========================================================

-- DELETE FROM productos_producto;

-- TRUNCATE TABLE productos_producto RESTART IDENTITY;